[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/event/java-vs-python"
  to = "/events/why-python-is-so-popular"
  status = 301

[[redirects]]
  from = "/event/http-caching-varnish"
  to = "/events/http-caching-varnish"
  status = 301

[[redirects]]
  from = "/event/12-anniversary"
  to = "/events"
  status = 301
